# -*- coding: utf-8 -*-
# KORRIGIERT: Syntaxfehler im Docstring behoben (Zeile 2-8)
"""rpg_game_logic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12k8eGP7IeJPL7uj0Ii4iRqSxa_VAHjma
"""

# Generated/Overwritten on: 2025-04-14 05:45:00 # Zeitpunkt aktualisiert
# rpg_game_logic.py
# V11: Further increased Mana/Energy regeneration

import math, random
from collections import defaultdict
from typing import Optional, Dict, List, Union, Any

# Importiere globale Konstanten für Ressourcen-Regeneration (V11 Anpassung)
try:
    ENERGY_REGEN_PER_TURN = 25  # War 20 (V10), Ursprünglich 15
    STAMINA_REGEN_PER_TURN = 20 # Bleibt bei 20 (V10)
    MANA_REGEN_PER_TURN = 10    # War 8 (V10), Ursprünglich 5
    print(f"INFO (rpg_game_logic): Regeneration rates set (M:{MANA_REGEN_PER_TURN}, S:{STAMINA_REGEN_PER_TURN}, E:{ENERGY_REGEN_PER_TURN})")
except Exception as e:
    ENERGY_REGEN_PER_TURN, STAMINA_REGEN_PER_TURN, MANA_REGEN_PER_TURN = 15, 15, 5
    print(f"WARNUNG (rpg_game_logic): Fehler beim Setzen der Regen-Raten, Fallback auf Standard (M:5, S:15, E:15). Fehler: {e}")


# Importiere Skill-Mapping direkt aus Definitionen
try:
    # Assuming rpg_definitions.py exists in the same directory or path
    # You might need to create this file or adjust the import path
    from rpg_definitions import ALL_SKILLS_MAP as SKILLS_BY_TYPE_MAP
except ImportError:
    print("FEHLER (rpg_game_logic): Konnte Skill-Mapping nicht importieren! Skills werden fehlen.")
    SKILLS_BY_TYPE_MAP = {} # Provide an empty fallback

# --- Skill Klasse (unverändert zu V9) ---
class Skill:
    """Represents a skill or ability a character can use."""
    def __init__(self, name: str, cost: int = 0, cost_type: str = "mana", cooldown: int = 0, target_type: str = "enemy", effect_type: str = "damage", power: int = 0, element: Optional[str] = None, duration: int = 0, modifiers: Optional[Dict[str, Union[int, float]]] = None):
        """
        Initializes a Skill object.

        Args:
            name: The name of the skill.
            cost: The resource cost to use the skill.
            cost_type: The type of resource used ('mana', 'stamina', 'energy').
            cooldown: The number of turns before the skill can be used again.
            target_type: Who the skill targets ('enemy', 'self', 'ally').
            effect_type: The primary effect of the skill ('damage', 'heal', 'buff', 'debuff').
            power: The base power/magnitude of the skill's effect.
            element: The elemental type of the skill (e.g., 'fire', 'physical').
            duration: The duration of the skill's effect in turns (0 for instant, 9999 for permanent).
            modifiers: A dictionary of additional effects (e.g., {'mod_angriff': 10, 'dot_damage': 5}).
        """
        self.name = name
        self.cost = cost
        self.cost_type = cost_type.lower() # Ensure lowercase for consistency
        self.cooldown = cooldown
        self.target_type = target_type
        self.effect_type = effect_type
        self.power = power
        self.element = element
        self.duration = duration
        self.modifiers = modifiers if modifiers is not None else {}

    def __repr__(self) -> str:
        """Provides a detailed string representation for debugging."""
        parts = [f"'{self.name}'"]
        if self.cost > 0:
            parts.append(f"cost={self.cost} {self.cost_type}")
        else:
            parts.append("cost=0")
        if self.cooldown > 0:
            parts.append(f"cd={self.cooldown}")
        parts.append(f"target='{self.target_type}'")
        parts.append(f"effect='{self.effect_type}'")
        if self.power != 0:
            parts.append(f"pow={self.power}")
        if self.element:
            parts.append(f"ele='{self.element}'")
        if self.duration == 9999:
             parts.append("dur=Permanent")
        elif self.duration > 0:
            parts.append(f"dur={self.duration}")
        if self.modifiers:
            parts.append(f"mods={self.modifiers}")
        return f"Skill({', '.join(parts)})"

    def __str__(self) -> str:
        """Provides a user-friendly string representation."""
        return self.__repr__() # Use the detailed representation for now

    def __eq__(self, other):
        """Checks equality based on skill name."""
        if not isinstance(other, Skill):
            return NotImplemented
        return self.name == other.name

    def __hash__(self):
        """Allows skills to be used in sets or as dictionary keys based on name."""
        return hash(self.name)

# --- Character Klasse (unverändert zu V9, außer _assign_skills Anpassung) ---
class Character:
    """Represents a character (player or NPC) in the game."""
    def __init__(self, name: str, class_name: str, level: int, char_definitions: dict, skill_definitions: dict):
        """
        Initializes a Character object.

        Args:
            name: The character's name.
            class_name: The character's class or type (e.g., 'Krieger', 'Goblin').
            level: The character's starting level.
            char_definitions: A dictionary containing base attributes for different character classes.
            skill_definitions: A dictionary mapping skill names to Skill objects.
        """
        self.name = name
        self.level = max(1, level) # Ensure level is at least 1

        if class_name not in char_definitions:
            raise ValueError(f"Unbekannte Klasse/Typ '{class_name}'")
        self.class_name = class_name
        # Copy base attributes to avoid modifying the original definition
        self.base_attributes = char_definitions[class_name].copy()

        self.current_xp = 0
        self.xp_to_next_level = self._calculate_xp_for_level(self.level + 1)

        # Store skill definitions for potential future reference (e.g., learning new skills)
        self._skill_definitions = skill_definitions

        # Calculate initial derived stats
        self._recalculate_derived_stats()

        # Initialize current resources to maximum
        self.current_hp = self.max_hp
        self.current_mana = self.max_mana
        self.current_stamina = self.max_stamina
        self.current_energy = self.max_energy

        # Assign skills based on class
        self.skills: List[Skill] = self._assign_skills()

        # Track skill cooldowns and active status effects
        self.cooldowns: Dict[str, int] = {skill.name: 0 for skill in self.skills}
        self.active_effects: Dict[str, Dict[str, Any]] = {} # {effect_name: {duration: X, modifiers: {...}, element: Y, stacks: Z}}

    def _assign_skills(self) -> List[Skill]:
        """Assigns skills to the character based on their class using SKILLS_BY_TYPE_MAP."""
        assigned_skills = []
        # Get the list of skill names for this character's type/class
        skill_names_for_type = SKILLS_BY_TYPE_MAP.get(self.class_name, [])

        for name in skill_names_for_type:
            skill_obj = self._skill_definitions.get(name)
            if skill_obj and isinstance(skill_obj, Skill):
                assigned_skills.append(skill_obj)
            else:
                # Log a warning if a skill defined in the map isn't found or isn't a Skill object
                print(f"WARNUNG (assign_skills): Skill '{name}' für Typ '{self.class_name}' nicht in skill_definitions gefunden oder kein Skill-Objekt.")
        return assigned_skills

    def _calculate_xp_for_level(self, target_level: int) -> int:
        """Calculates the total XP required to reach a target level."""
        # Simple linear progression for now
        base_xp_per_level = 100
        # XP needed is the total XP for the target level minus total XP for current level
        # For level 1->2, need 100 * (2-1) = 100
        # For level 2->3, need 100 * (3-1) = 200 (total), so 100 more than level 2
        xp_needed = base_xp_per_level * max(0, target_level - 1)
        # If target_level is the *next* level, this calculates the XP needed *from the start of the current level*
        # We store the threshold needed to *reach* the next level.
        return xp_needed # This represents the XP *threshold* for the next level

    def _recalculate_derived_stats(self):
        """Calculates stats derived from base attributes and level."""
        # Get base attribute values, defaulting to 0 if not present
        str_val = self.base_attributes.get('str', 0)
        ges_val = self.base_attributes.get('ges', 0)
        kon_val = self.base_attributes.get('kon', 0)
        int_val = self.base_attributes.get('int', 0)
        wei_val = self.base_attributes.get('wei', 0)
        lvl = self.level

        # Store current HP and Max HP before recalculation
        hp_before = getattr(self, 'current_hp', None) # Use getattr for safety before init
        max_hp_before = getattr(self, 'max_hp', 0)

        # --- Calculate Max Resources ---
        # HP: Based on KON and level
        self.max_hp = math.ceil((kon_val * 10) + (lvl * 5) + 20)
        # Other resources: Directly from base attributes (can be adjusted later)
        self.max_mana = self.base_attributes.get('man', 0) # Use 'man' from definitions
        self.max_stamina = self.base_attributes.get('stm', 0) # Use 'stm'
        self.max_energy = self.base_attributes.get('eng', 0) # Use 'eng'

        # --- Calculate Combat Stats ---
        # Angriff (Attack Power): Primarily STR based
        self.base_angriff = math.ceil(str_val * 2)

        # Magiekraft (Magic Power): Based on INT for Mages, WEI for Kleriker, mix for some monsters
        if self.class_name == "Magier":
            self.base_magiekraft = math.ceil(int_val * 2)
        elif self.class_name == "Kleriker":
            self.base_magiekraft = math.ceil(wei_val * 2)
        elif self.class_name in ["Goblin", "Skelett", "Ork"]: # Example monster scaling
             self.base_magiekraft = max(1, math.ceil(int_val * 1.0 + wei_val * 0.5)) # Ensure at least 1
        else: # Default for other classes (e.g., Krieger, Schurke)
            self.base_magiekraft = 1 # Minimal magic power unless specified

        # Verteidigung (Defense): Based on KON and some STR
        self.base_verteidigung = math.ceil((kon_val * 1) + (str_val * 0.5))
        # Genauigkeit (Accuracy): Base chance + GES bonus
        self.base_genauigkeit = math.ceil(75 + (ges_val * 1)) # Base 75% hit chance
        # Ausweichen (Evasion): Base chance + GES bonus
        self.base_ausweichen = math.ceil(5 + (ges_val * 1)) # Base 5% evasion
        # Kritische Trefferchance (Crit Chance): Base chance + GES bonus
        self.base_krit_chance = 1.0 + (ges_val * 0.5) # Base 1% + 0.5% per GES
        # Kritischer Trefferfaktor (Crit Damage Multiplier): Base multiplier + GES bonus
        self.base_krit_faktor = 1.5 + (ges_val * 0.02) # Base 150% + 2% per GES

        # --- Adjust Current HP after Max HP change ---
        hp_increase = self.max_hp - max_hp_before
        if hp_before is not None and hp_increase > 0:
            # If max HP increased, increase current HP by the same amount (up to new max)
            self.current_hp = min(self.max_hp, hp_before + hp_increase)
        elif hp_before is None: # First time calculation during __init__
             self.current_hp = self.max_hp

        # --- Cap Current Resources ---
        # Ensure current resources don't exceed the (potentially new) maximums
        self.current_mana = min(getattr(self, 'current_mana', self.max_mana), self.max_mana)
        self.current_stamina = min(getattr(self, 'current_stamina', self.max_stamina), self.max_stamina)
        self.current_energy = min(getattr(self, 'current_energy', self.max_energy), self.max_energy)


    def get_stat(self, stat_name: str) -> Union[int, float]:
        """
        Gets the final value of a stat, including modifications from active effects.

        Args:
            stat_name: The name of the stat to retrieve (case-insensitive).
                       Handles base attributes ('str', 'ges', etc.), derived stats
                       ('angriff', 'verteidigung', etc.), and current/max resources.

        Returns:
            The calculated value of the stat, or 0 if unknown.
        """
        stat_name_lower = stat_name.lower()

        # 1. Check if it's a base attribute
        if stat_name_lower in ['str', 'ges', 'kon', 'int', 'wei']:
            # Base attributes are not typically modified by effects in this setup
            return self.base_attributes.get(stat_name_lower, 0)

        # 2. Check if it's a calculated base stat (like 'base_angriff')
        base_attr_calculated_name = f"base_{stat_name_lower}"
        if hasattr(self, base_attr_calculated_name):
            base_value = getattr(self, base_attr_calculated_name)
            # Calculate sum of modifiers from active effects
            mod_sum = 0
            # Construct the modifier key (e.g., 'mod_angriff', 'mod_verteidigung')
            mod_key = f"mod_{stat_name_lower}"
            for effect_data in self.active_effects.values():
                modifiers = effect_data.get("modifiers", {})
                if isinstance(modifiers, dict): # Ensure modifiers is a dict
                    # Apply modifier based on stacks
                    mod_sum += modifiers.get(mod_key, 0) * effect_data.get("stacks", 1)

            # Apply minimum value constraints for certain stats
            min_val = 1 if stat_name_lower in ["angriff", "verteidigung", "magiekraft"] else 0
            # Return base value + modifiers, respecting minimum value
            return max(min_val, math.ceil(base_value + mod_sum))

        # 3. Check for current/max resources or level/XP info
        elif stat_name_lower in ['max_hp', 'current_hp', 'max_mana', 'current_mana',
                                 'max_stamina', 'current_stamina', 'max_energy', 'current_energy',
                                 'level', 'current_xp', 'xp_to_next_level']:
            return getattr(self, stat_name_lower, 0) # Return the direct attribute value

        # 4. Check if it's another direct attribute of the class (less common)
        elif hasattr(self, stat_name):
             return getattr(self, stat_name)

        # 5. Stat not found
        else:
            print(f"WARNUNG (get_stat): Unbekannter Stat '{stat_name}' angefragt für {self.name}.")
            return 0

    def gain_xp(self, amount: int):
        """
        Adds XP to the character and handles level ups. Only applies to 'Hero' types.

        Args:
            amount: The amount of XP to gain.
        """
        # Only heroes gain XP in this design
        if "Hero" not in self.name: # Simple check, could be made more robust
             return

        if amount <= 0 or self.is_dead():
            return # No XP gain if dead or amount is non-positive

        self.current_xp += amount
        print(f"{self.name} erhält {amount} XP. (Aktuell: {self.current_xp}/{self.xp_to_next_level})")

        # Check for level up(s) - loop in case of multiple level ups from one XP gain
        # xp_to_next_level stores the *threshold* to reach the next level
        while self.xp_to_next_level > 0 and self.current_xp >= self.xp_to_next_level:
             self._level_up()

        # If max level reached (xp_to_next_level becomes 0 or negative), cap XP
        if self.xp_to_next_level <= 0:
             self.current_xp = 0 # Or set to a max value if desired


    def _level_up(self):
        """Handles the process of leveling up."""
        # This check might be redundant if gain_xp already checks, but good for safety
        if "Hero" not in self.name:
            return

        level_before = self.level
        xp_needed_for_current_level = self.xp_to_next_level # Threshold just passed
        xp_overflow = self.current_xp - xp_needed_for_current_level # XP towards the *next* level

        self.level += 1
        self.current_xp = max(0, xp_overflow) # Keep overflow XP

        print(f"LEVEL UP! {self.name} ist jetzt Level {self.level}!")

        # Calculate XP needed for the *new* next level
        self.xp_to_next_level = self._calculate_xp_for_level(self.level + 1)
        # Handle max level case (optional)
        # if self.level >= MAX_LEVEL:
        #    self.xp_to_next_level = 0 # Indicate max level

        # --- Stat Increases ---
        leveled_up_attributes = []
        # Example: Always increase KON
        kon_increase = 1
        self.base_attributes['kon'] = self.base_attributes.get('kon', 0) + kon_increase
        leveled_up_attributes.append(f"KON +{kon_increase}")

        # Example: Increase main stat based on class
        main_attr_increase = 1 # Could vary
        if self.class_name == "Krieger":
            self.base_attributes['str'] = self.base_attributes.get('str', 0) + main_attr_increase
            leveled_up_attributes.append(f"STR +{main_attr_increase}")
        elif self.class_name == "Magier":
            self.base_attributes['int'] = self.base_attributes.get('int', 0) + main_attr_increase
            leveled_up_attributes.append(f"INT +{main_attr_increase}")
        elif self.class_name == "Schurke":
            self.base_attributes['ges'] = self.base_attributes.get('ges', 0) + main_attr_increase
            leveled_up_attributes.append(f"GES +{main_attr_increase}")
        elif self.class_name == "Kleriker":
            self.base_attributes['wei'] = self.base_attributes.get('wei', 0) + main_attr_increase
            leveled_up_attributes.append(f"WEI +{main_attr_increase}")
        # Add more class-specific increases or choices later

        print(f"Attribute erhöht: {', '.join(leveled_up_attributes)}")

        # --- Recalculate Derived Stats & Heal ---
        hp_before_recalc = self.current_hp
        max_hp_before = self.max_hp # Store max HP before recalculation

        self._recalculate_derived_stats() # Update max HP, attack, defense, etc.

        # Calculate HP gained specifically from the level up (due to KON/level increase)
        hp_gained_from_level_up = self.max_hp - max_hp_before
        # Restore HP: Current HP + HP gained from level up, capped at new max HP
        self.current_hp = min(self.max_hp, hp_before_recalc + hp_gained_from_level_up)
        print(f"{self.name} regeneriert beim Level Up (+{max(0, hp_gained_from_level_up)} HP).")


        # --- Refill Resources ---
        self.current_mana = self.max_mana
        self.current_stamina = self.max_stamina
        self.current_energy = self.max_energy
        print(f"{self.name} Ressourcen aufgefüllt.")

        # --- Learn New Skills (Optional) ---
        # Add logic here to check if new skills are learned at this level


    def can_use_skill(self, skill: Skill) -> bool:
        """
        Checks if the character can currently use the specified skill.

        Args:
            skill: The Skill object to check.

        Returns:
            True if the skill can be used, False otherwise.
        """
        # 1. Validate Skill Object and Ownership
        is_valid_skill_obj = isinstance(skill, Skill)
        # Check if the skill object is actually in the character's known skills
        belongs_to_char = skill in self.skills if is_valid_skill_obj else False
        if not is_valid_skill_obj or not belongs_to_char:
            # print(f"DEBUG: can_use_skill: Invalid or unknown skill object for {self.name}: {skill}") # Optional Debug
            return False

        skill_name = getattr(skill, 'name', None)
        if skill_name is None: return False # Should not happen if it's a valid Skill object

        # 2. Check Cooldown
        if self.cooldowns.get(skill_name, 0) > 0:
            # print(f"DEBUG: can_use_skill: Skill '{skill_name}' on cooldown for {self.name} ({self.cooldowns[skill_name]} turns left)") # Optional Debug
            return False

        # 3. Check Resource Cost
        cost = skill.cost
        if cost <= 0:
            return True # No cost, usable if not on cooldown

        cost_type = skill.cost_type
        can_afford = False
        if cost_type == "mana":
            can_afford = self.current_mana >= cost
        elif cost_type == "stamina":
            can_afford = self.current_stamina >= cost
        elif cost_type == "energy":
            can_afford = self.current_energy >= cost
        else:
            print(f"WARNUNG (can_use_skill): Unbekannter Kostentyp '{cost_type}' für Skill '{skill_name}'")
            return False # Unknown cost type

        # if not can_afford:
            # print(f"DEBUG: can_use_skill: Not enough {cost_type} for {self.name} to use '{skill_name}' (needs {cost}, has {getattr(self, f'current_{cost_type}')})") # Optional Debug

        return can_afford

    def use_skill(self, skill: Skill, target: 'Character'):
        """
        Uses a skill on a target, applying costs, cooldowns, and effects.

        Args:
            skill: The Skill object to use.
            target: The Character object being targeted.
        """
        # Double-check usability (although usually checked before calling)
        if not self.can_use_skill(skill):
            # print(f"WARNUNG: use_skill für {self.name} mit Skill '{getattr(skill,'name','N/A')}' aufgerufen, obwohl can_use_skill False ist!") # Keep if needed
            return

        print(f"{self.name} benutzt '{skill.name}' auf {target.name}.") # Basic log

        # 1. Apply Cost
        cost = skill.cost
        if cost > 0:
            cost_type = skill.cost_type
            if cost_type == "mana":
                self.current_mana = max(0, self.current_mana - cost)
            elif cost_type == "stamina":
                self.current_stamina = max(0, self.current_stamina - cost)
            elif cost_type == "energy":
                self.current_energy = max(0, self.current_energy - cost)
            # print(f"DEBUG: {self.name} paid {cost} {cost_type}. Remaining: {getattr(self, f'current_{cost_type}')}") # Optional Debug

        # 2. Apply Cooldown
        if skill.cooldown > 0:
            # Cooldown starts *after* the turn it's used. +1 makes it unavailable next turn.
            self.cooldowns[skill.name] = skill.cooldown + 1
            # print(f"DEBUG: Skill '{skill.name}' cooldown set to {self.cooldowns[skill.name]} for {self.name}") # Optional Debug


        # 3. Determine Actual Target
        # Simplistic target logic for now (assumes 'enemy' or 'self')
        actual_target = target if skill.target_type == "enemy" else self
        # Could add 'ally', 'all_enemies', 'all_allies', 'random_enemy' etc. later

        # 4. Apply Effect
        effect_type = skill.effect_type

        if effect_type == "damage":
            # --- Damage Calculation ---
            # Check if magical or physical based on element
            is_magic = skill.element and skill.element != 'physical' # Assume non-physical elements are magic

            if not is_magic:
                # Physical Damage: Angriff vs Verteidigung
                attacker_stat = self.get_stat('angriff')
                defender_stat = actual_target.get_stat('verteidigung')
                # print(f"DEBUG: Physical Damage - Attacker Angriff: {attacker_stat}, Defender Verteidigung: {defender_stat}") # Keep debug off by default
            else:
                # Magical Damage: Magiekraft vs Verteidigung (or a separate magic defense stat)
                attacker_stat = self.get_stat('magiekraft')
                # Using regular defense for now, could add 'magie_verteidigung' later
                defender_stat = actual_target.get_stat('verteidigung')
                # print(f"DEBUG: Magic Damage ({skill.element}) - Attacker Magiekraft: {attacker_stat}, Defender Verteidigung: {defender_stat}") # Keep debug off by default

            # Basic damage formula: Skill Power + Attacker Stat - Defender Stat
            # Ensure minimum damage (e.g., 1)
            damage = max(1, math.ceil(skill.power + attacker_stat - defender_stat))

            # Add critical hit check (optional)
            # crit_roll = random.uniform(0, 100)
            # if crit_roll < self.get_stat('krit_chance'):
            #     crit_multiplier = self.get_stat('krit_faktor')
            #     damage = math.ceil(damage * crit_multiplier)
            #     print("KRITISCHER TREFFER!")

            # Add accuracy/evasion check (optional)
            # hit_roll = random.uniform(0, 100)
            # chance_to_hit = self.get_stat('genauigkeit') - actual_target.get_stat('ausweichen')
            # if hit_roll > chance_to_hit:
            #     print(f"{actual_target.name} weicht aus!")
            #     damage = 0 # Miss

            if damage > 0:
                 print(f"{actual_target.name} erleidet {damage} Schaden.")
                 actual_target.take_damage(damage)

        elif effect_type == "heal":
            # --- Healing Calculation ---
            # Base heal amount + caster's Magiekraft (or WEI for Kleriker?)
            # Using Magiekraft for simplicity now
            heal_amount = max(0, math.ceil(skill.power + self.get_stat('magiekraft')))
            print(f"{actual_target.name} wird um {heal_amount} HP geheilt.")
            actual_target.heal_hp(heal_amount)

        elif effect_type in ["buff", "debuff"]:
            # --- Apply Status Effect ---
            print(f"Effekt '{skill.name}' wird auf {actual_target.name} angewendet (Dauer: {skill.duration}, Mods: {skill.modifiers}).")
            actual_target.apply_effect(skill.name, skill.duration, skill.modifiers, skill.element)

        # Add other effect types like 'summon', 'resource_drain', 'control' etc. later

    def take_damage(self, amount: int):
        """Reduces character's HP by the given amount (minimum 1)."""
        # Ensure damage is at least 1, unless specified otherwise
        damage_taken = max(1, amount)
        self.current_hp = max(0, self.current_hp - damage_taken) # Prevent HP going below 0
        # print(f"DEBUG: {self.name} takes {damage_taken} damage. HP remaining: {self.current_hp}") # Optional Debug
        if self.is_dead():
             print(f"{self.name} wurde besiegt!")

    def heal_hp(self, amount: int):
        """Increases character's HP by the given amount, capped by max HP."""
        heal_done = max(0, amount) # Ensure healing is not negative
        hp_before = self.current_hp
        self.current_hp = min(self.max_hp, self.current_hp + heal_done)
        # print(f"DEBUG: {self.name} healed {heal_done} HP. HP: {self.current_hp}/{self.max_hp}") # Optional Debug
        # return self.current_hp - hp_before # Return actual amount healed

    def apply_effect(self, name: str, duration: int, mods: dict, element: Optional[str] = None):
        """
        Applies a status effect (buff/debuff) to the character.
        Handles stacking or refreshing based on future implementation needs.

        Args:
            name: The unique name of the effect (often the skill name).
            duration: How many turns the effect lasts (9999 for permanent).
            mods: The dictionary of modifiers applied by the effect.
            element: Optional element associated with the effect (e.g., for resistances).
        """
        # Simple overwrite/refresh logic for now. Could add stacking later.
        # Example stacking logic:
        # if name in self.active_effects and mods.get('stackable', False):
        #    max_stacks = mods.get('max_stacks', 3) # Default max 3 stacks
        #    current_stacks = self.active_effects[name].get('stacks', 1)
        #    self.active_effects[name]['stacks'] = min(max_stacks, current_stacks + 1)
        #    # Refresh duration on stack application
        #    self.active_effects[name]['duration'] = duration # Or max(self.active_effects[name]['duration'], duration)
        #    print(f"DEBUG: Effect '{name}' stacked on {self.name} ({self.active_effects[name]['stacks']} stacks).")
        # else:
        # Apply effect normally (or overwrite if not stackable/first application)
        self.active_effects[name] = {
            "duration": duration,
            "modifiers": mods.copy(), # Copy mods to prevent interference
            "element": element,
            "stacks": 1 # Start with 1 stack
        }
        # print(f"DEBUG: Effect '{name}' applied to {self.name}. Data: {self.active_effects[name]}") # Optional Debug


    # apply_and_tick_effects mit erhöhter Regeneration (V11)
    def apply_and_tick_effects(self):
        """
        Applies effects like DoT/HoT, ticks down durations and cooldowns,
        and handles passive resource regeneration at the start/end of a turn.
        (V11 includes increased regeneration rates).
        """
        # --- Tick Cooldowns ---
        # Iterate over a copy of keys in case cooldowns dict changes (unlikely here)
        for name in list(self.cooldowns.keys()):
            if self.cooldowns[name] > 0:
                self.cooldowns[name] = max(0, self.cooldowns[name] - 1)
                # if self.cooldowns[name] == 0:
                #    print(f"DEBUG: Skill '{name}' ready for {self.name}.") # Optional Debug

        # --- Tick and Apply Active Effects ---
        to_remove = [] # List of effect names to remove after iteration
        # Iterate over a copy of keys because the dictionary might change during iteration
        active_effect_keys = list(self.active_effects.keys())

        for name in active_effect_keys:
            # Check if the effect still exists (it might have been removed by another effect)
            if name not in self.active_effects:
                continue

            data = self.active_effects[name]
            mods = data.get("modifiers", {})
            stacks = data.get("stacks", 1)

            # Apply Damage over Time (DoT)
            dot_damage = mods.get("dot_damage", 0) * stacks
            if dot_damage > 0:
                actual_dot = math.ceil(dot_damage) # Apply ceiling to ensure at least 1 if > 0
                print(f"{self.name} erleidet {actual_dot} Schaden durch '{name}'.")
                self.take_damage(actual_dot)
                # If character dies from DoT, stop processing further effects for this turn
                if self.is_dead():
                    print(f"DEBUG: {self.name} died from DoT effect '{name}'.")
                    break # Exit the effect processing loop for this character

            # Apply Heal over Time (HoT)
            hot_heal = mods.get("dot_heal", 0) * stacks
            # Only apply HoT if the character is still alive
            if hot_heal > 0 and not self.is_dead():
                actual_hot = math.ceil(hot_heal)
                print(f"{self.name} heilt {actual_hot} HP durch '{name}'.")
                self.heal_hp(actual_hot)

            # Apply Resource Regeneration/Drain from effects (optional)
            # mana_regen_mod = mods.get("mod_mana_regen", 0) * stacks
            # self.current_mana = min(self.max_mana, max(0, self.current_mana + mana_regen_mod))
            # stamina_regen_mod = mods.get("mod_stamina_regen", 0) * stacks
            # self.current_stamina = min(self.max_stamina, max(0, self.current_stamina + stamina_regen_mod))
            # energy_regen_mod = mods.get("mod_energy_regen", 0) * stacks
            # self.current_energy = min(self.max_energy, max(0, self.current_energy + energy_regen_mod))


            # Tick down duration (unless permanent)
            if data["duration"] != 9999: # 9999 signifies permanent
                data["duration"] -= 1
                if data["duration"] <= 0:
                    to_remove.append(name)
                    # Don't print expiration message if the character just died
                    if not self.is_dead():
                         print(f"Effekt '{name}' auf {self.name} ist abgelaufen.")

        # Remove expired effects
        for name in to_remove:
            if name in self.active_effects: # Check again in case it was removed mid-loop
                del self.active_effects[name]

        # --- Passive Resource Regeneration (End of Turn / Start of Next Turn) ---
        # Only regenerate if alive after all effects have ticked
        if not self.is_dead():
            # Use the globally defined regeneration rates (V11 values)
            mana_regen = MANA_REGEN_PER_TURN
            stamina_regen = STAMINA_REGEN_PER_TURN
            energy_regen = ENERGY_REGEN_PER_TURN

            # Add regeneration from effects (optional, could be done above too)
            # Example: mana_regen += self.get_stat('mana_regen_bonus')

            self.current_mana = min(self.max_mana, self.current_mana + mana_regen)
            self.current_stamina = min(self.max_stamina, self.current_stamina + stamina_regen)
            self.current_energy = min(self.max_energy, self.current_energy + energy_regen)
            # print(f"DEBUG: {self.name} regenerated resources. M:{self.current_mana}, S:{self.current_stamina}, E:{self.current_energy}") # Optional


    def is_dead(self) -> bool:
        """Checks if the character's HP is 0 or less."""
        return self.current_hp <= 0

    def __str__(self):
        """Provides a comprehensive string summary of the character's status."""
        # HP Status
        hp_str = f"HP:{int(self.current_hp)}/{self.max_hp}" # Use int() for cleaner display

        # XP Status (only for Heroes)
        xp_str = ""
        if "Hero" in self.name:
             xp_to_next = getattr(self, 'xp_to_next_level', 0)
             # Display "(MAX)" if xp_to_next_level is 0 or less (indicating max level reached)
             xp_next_display = xp_to_next if xp_to_next > 0 else "(MAX)"
             xp_str = f"XP:{self.current_xp}/{xp_next_display}"

        # Resource Status (Mana, Stamina, Energy) - only show if max > 0
        res_parts = []
        if self.max_mana > 0:
            res_parts.append(f"M:{int(self.current_mana)}/{self.max_mana}")
        if self.max_stamina > 0:
            res_parts.append(f"S:{int(self.current_stamina)}/{self.max_stamina}")
        if self.max_energy > 0:
            res_parts.append(f"E:{int(self.current_energy)}/{self.max_energy}")
        res_str = " ".join(res_parts)

        # Base Attributes Summary (using get_stat to include potential future mods)
        attr_str = f"Atr:[S:{self.get_stat('str')} G:{self.get_stat('ges')} K:{self.get_stat('kon')} I:{self.get_stat('int')} W:{self.get_stat('wei')}]"

        # Active Effects Summary
        eff_str = ""
        eff_parts = []
        if self.active_effects:
            # Sort effects alphabetically for consistent display
            for name, data in sorted(self.active_effects.items()):
                dur = data.get('duration', 0)
                dur_s = f"{dur}" if dur != 9999 else "∞" # Display ∞ for permanent
                stacks = data.get('stacks', 1)
                stack_s = f"x{stacks}" if stacks > 1 else ""
                eff_parts.append(f"{name}({dur_s}{stack_s})")
        if eff_parts:
            eff_str = " Eff:[" + ", ".join(eff_parts) + "]" # Add brackets and comma separation

        # Combine all parts
        # Example: "Hero Krieger (Krieger L:5) HP:100/120 XP:50/200 M:30/30 S:50/50 Atr:[S:15 G:10 K:12 I:5 W:8] Eff:[Stärkung(3), Giftpfeil(2∞x2)]"
        final_parts = [
            f"{self.name} ({self.class_name} L:{self.level})",
            hp_str
        ]
        if xp_str: final_parts.append(xp_str)
        if res_str: final_parts.append(res_str)
        final_parts.append(attr_str)
        if eff_str: final_parts.append(eff_str)

        return " ".join(final_parts)


# --- Environment Klasse (Platzhalter) ---
class Environment:
    """Manages the characters and game state within a specific context (e.g., a combat encounter)."""
    def __init__(self):
        self.characters: List[Character] = []
        self.round: int = 0 # Track combat rounds
        # Add turn order logic if needed (e.g., based on speed/initiative)
        # self.turn_order: List[Character] = []

    def add_character(self, char: Character):
        """Adds a character to the environment."""
        if isinstance(char, Character):
             if char not in self.characters: # Prevent adding duplicates
                 self.characters.append(char)
             else:
                 print(f"WARNUNG (Environment): Charakter {char.name} ist bereits in der Umgebung.")
        else:
             print(f"WARNUNG (Environment): Versuch, ungültiges Objekt hinzuzufügen: {char}")

    def remove_character(self, char: Character):
        """Removes a character from the environment."""
        if char in self.characters:
            self.characters.remove(char)
        else:
             print(f"WARNUNG (Environment): Versuch, Charakter {char.name} zu entfernen, der nicht in der Umgebung ist.")


    def get_living_characters(self) -> List[Character]:
        """Returns a list of characters in the environment who are not dead."""
        return [c for c in self.characters if not c.is_dead()]

    def get_characters_by_team(self, team_affiliation: str) -> List[Character]:
        """
        Returns living characters belonging to a specific team.
        Requires a 'team' attribute on the Character class for robust implementation.
        """
        # Placeholder: Using name convention ("Hero" vs not "Hero")
        # TODO: Add a 'team' attribute to Character class for better team management
        living_chars = self.get_living_characters()
        if team_affiliation.lower() == 'player' or team_affiliation.lower() == 'hero':
            return [c for c in living_chars if "Hero" in c.name]
        elif team_affiliation.lower() == 'enemy':
            return [c for c in living_chars if "Hero" not in c.name]
        # Add other potential affiliations like 'neutral', 'ally' etc. if needed
        else:
            print(f"WARNUNG (get_characters_by_team): Unbekannte Team-Zugehörigkeit '{team_affiliation}'")
            return []


    def is_combat_over(self) -> bool:
        """
        Checks if the combat has ended.
        Condition: Only one team (or zero teams) has living members remaining.
        """
        living_chars = self.get_living_characters()
        if not living_chars:
            return True # Everyone is dead

        # Check teams based on placeholder name convention
        # TODO: Replace with actual team attribute check
        living_teams = set()
        if any("Hero" in c.name for c in living_chars):
            living_teams.add("player")
        if any("Hero" not in c.name for c in living_chars):
            living_teams.add("enemy")

        # Combat is over if 1 or 0 teams remain
        return len(living_teams) <= 1

    def start_turn(self, character: Character):
         """Processes start-of-turn effects for a character."""
         # Ensure character is actually alive before starting turn
         if character.is_dead():
             print(f"DEBUG: Skipping start_turn for dead character {character.name}")
             return

         print(f"\n--- Zug von {character.name} (Runde {self.round}) ---")
         # Apply DoTs/HoTs, tick durations/cooldowns, regenerate resources
         character.apply_and_tick_effects()
         # Print status *after* start-of-turn effects (including potential death from DoT)
         print(character)

    def end_round(self):
        """Processes end-of-round actions."""
        self.round += 1
        print(f"\n--- Ende von Runde {self.round - 1} ---") # Display the round that just ended
        # Potential end-of-round effects or checks can go here
        # e.g., check for environmental hazards, summon reinforcements etc.

    def run_combat(self):
        """Runs the main combat loop."""
        print("\n=== KAMPF BEGINNT ===")
        self.round = 1
        # Optional: Determine initial turn order here
        # self.turn_order = sorted(self.characters, key=lambda c: c.get_stat('geschwindigkeit'), reverse=True) # Example

        while not self.is_combat_over():
            print(f"\n=== Runde {self.round} ===")
            # Use a fixed order or recalculate turn order each round if initiative changes
            # current_turn_order = self.get_living_characters() # Simple order for now
            # Optional: Sort by speed/initiative
            current_turn_order = sorted(self.get_living_characters(), key=lambda c: c.get_stat('ges'), reverse=True)


            for char in current_turn_order:
                # Check if combat ended mid-round (e.g., due to DoT)
                if self.is_combat_over():
                    break

                # Check if the character is still alive (might have died from another char's action this round)
                if char.is_dead():
                    continue

                # --- Start Turn ---
                self.start_turn(char)

                # Check if character died from start-of-turn effects (e.g., DoT)
                if char.is_dead():
                    continue

                # --- Action Phase ---
                # TODO: Replace simple AI with more sophisticated logic or player input handling
                target = None
                skill_to_use = None

                if "Hero" in char.name: # Player's turn logic
                    # Find living enemies
                    enemies = self.get_characters_by_team('enemy')
                    if enemies:
                        target = random.choice(enemies) # Target random living enemy for now
                        # Simple AI: Prioritize skills if usable, otherwise basic attack
                        # Example: Try defense buff first?
                        defense_skill = next((s for s in char.skills if s.name == "Verteidigungshaltung"), None)
                        schlag_skill = next((s for s in char.skills if s.name == "Schlag"), None) # Assuming Krieger has Schlag

                        if defense_skill and char.can_use_skill(defense_skill) and "Verteidigungshaltung" not in char.active_effects:
                             skill_to_use = defense_skill
                             target = char # Target self for buff
                        elif schlag_skill and char.can_use_skill(schlag_skill):
                            skill_to_use = schlag_skill
                        # Add more complex skill selection / player input prompt here
                        else:
                             print(f"{char.name} hat keine benutzbare Aktion.")


                else: # Enemy's turn logic (simple AI)
                    # Find living heroes
                    heroes = self.get_characters_by_team('player')
                    if heroes:
                        target = random.choice(heroes) # Target random living hero
                        # Simple AI: Prioritize specific skills
                        gift_skill = next((s for s in char.skills if s.name == "Giftpfeil"), None) # Check if Goblin has Giftpfeil
                        schlag_skill = next((s for s in char.skills if s.name == "Schlag"), None) # Check if Goblin has Schlag

                        # Try to apply DoT if target doesn't have it and skill is usable
                        has_gift_effect = any(eff_name == "Giftpfeil" for eff_name in target.active_effects)
                        if gift_skill and char.can_use_skill(gift_skill) and not has_gift_effect:
                             skill_to_use = gift_skill
                        elif schlag_skill and char.can_use_skill(schlag_skill):
                             skill_to_use = schlag_skill
                        else:
                             print(f"{char.name} hat keine benutzbare Aktion.")


                # --- Execute Action ---
                if skill_to_use and target:
                    # Ensure target is still valid (alive) before using skill
                    if target.is_dead():
                         print(f"{char.name} versucht, {skill_to_use.name} auf das besiegte Ziel {target.name} zu verwenden!")
                         # Optionally: Choose a new target or skip action
                         print(f"{char.name} tut stattdessen nichts.")
                    else:
                         char.use_skill(skill_to_use, target)
                         # Print status after action
                         print(char)
                         # Print target status only if it's a different character
                         if target != char:
                             print(target)
                else:
                    # Only print "tut nichts" if no action was possible
                    if not skill_to_use:
                         print(f"{char.name} tut nichts.")


            # --- End Round ---
            if not self.is_combat_over(): # Only proceed to next round if combat isn't over
                 self.end_round()
            else:
                 break # Exit the while loop if combat ended

        # --- Combat End ---
        print("\n=== KAMPF BEENDET ===")
        winner_list = self.get_living_characters()
        if not winner_list:
            print("Alle Kämpfer wurden besiegt! Unentschieden?")
        else:
            # Determine winning team (crude check based on names)
            if any("Hero" in c.name for c in winner_list):
                print("Sieg für die Helden!")
                # Grant XP to surviving heroes
                xp_gain = 50 # Example XP reward
                print(f"Überlebende Helden erhalten {xp_gain} XP.")
                for hero_char in winner_list:
                    if "Hero" in hero_char.name:
                        hero_char.gain_xp(xp_gain)
                        print(hero_char) # Show final status with XP gain/level up
            else:
                print("Sieg für die Gegner!")

        print("=====================")


# --- Beispielhafte Initialisierung (wenn die Datei direkt ausgeführt wird) ---
if __name__ == "__main__":
    print("\nrpg_game_logic.py wird direkt ausgeführt (Beispiel-Setup).")

    # --- Definitionen (Normalerweise in separater Datei: rpg_definitions.py) ---
    CHARACTER_DEFS = {
        "Krieger": {"str": 5, "ges": 3, "kon": 4, "int": 1, "wei": 2, "man": 10, "stm": 20, "eng": 15},
        "Magier": {"str": 1, "ges": 2, "kon": 3, "int": 5, "wei": 4, "man": 30, "stm": 10, "eng": 10},
        "Goblin": {"str": 2, "ges": 4, "kon": 2, "int": 1, "wei": 1, "man": 0, "stm": 15, "eng": 10},
        "Skelett": {"str": 3, "ges": 2, "kon": 3, "int": 1, "wei": 1, "man": 0, "stm": 10, "eng": 5}, # Added Skeleton
    }

    ALL_SKILLS = {
        # Physical
        "Schlag": Skill(name="Schlag", cost=5, cost_type="stamina", cooldown=0, target_type="enemy", effect_type="damage", power=5, element="physical"),
        "Mächtiger Schlag": Skill(name="Mächtiger Schlag", cost=10, cost_type="stamina", cooldown=1, target_type="enemy", effect_type="damage", power=12, element="physical"),
        # Magic
        "Feuerball": Skill(name="Feuerball", cost=10, cost_type="mana", cooldown=2, target_type="enemy", effect_type="damage", power=15, element="fire"),
        "Eispfeil": Skill(name="Eispfeil", cost=8, cost_type="mana", cooldown=1, target_type="enemy", effect_type="damage", power=10, element="ice", modifiers={"mod_ges": -2}), # Slows target
        # Healing
        "Heilung": Skill(name="Heilung", cost=8, cost_type="mana", cooldown=1, target_type="self", effect_type="heal", power=10), # Target self for now
        "Gruppenheilung": Skill(name="Gruppenheilung", cost=20, cost_type="mana", cooldown=4, target_type="ally", effect_type="heal", power=8), # Needs 'ally' target type logic
        # Buffs/Debuffs
        "Verteidigungshaltung": Skill(name="Verteidigungshaltung", cost=10, cost_type="energy", cooldown=3, target_type="self", effect_type="buff", duration=3, modifiers={"mod_verteidigung": 5}),
        "Schwächen": Skill(name="Schwächen", cost=5, cost_type="mana", cooldown=2, target_type="enemy", effect_type="debuff", duration=3, modifiers={"mod_angriff": -3}),
        "Giftpfeil": Skill(name="Giftpfeil", cost=5, cost_type="stamina", cooldown=1, target_type="enemy", effect_type="debuff", duration=4, modifiers={"dot_damage": 3, "stackable": True, "max_stacks": 3}, element="poison"), # Make it stackable
        "Flammenwand": Skill(name="Flammenwand", cost=15, cost_type="mana", cooldown=3, target_type="enemy", effect_type="debuff", duration=3, modifiers={"dot_damage": 5}, element="fire"), # Area effect needs different targeting
   }

    # Skill Mapping (Normalerweise in separater Datei: rpg_definitions.py)
    # Update SKILLS_BY_TYPE_MAP based on the global definition if not imported
    if not SKILLS_BY_TYPE_MAP: # If import failed, use this example map
        SKILLS_BY_TYPE_MAP = {
            "Krieger": ["Schlag", "Mächtiger Schlag", "Verteidigungshaltung"],
            "Magier": ["Feuerball", "Eispfeil", "Heilung", "Schwächen"], # Mage gets more utility
            "Goblin": ["Schlag", "Giftpfeil"],
            "Skelett": ["Schlag"], # Skeletons are simple
            # Add Kleriker, Schurke etc. later
        }
    # --- End Definitions ---


    # --- Spiel Setup ---
    try:
        # Erstelle Charaktere
        hero_krieger = Character(name="Hero Krieger", class_name="Krieger", level=3, char_definitions=CHARACTER_DEFS, skill_definitions=ALL_SKILLS)
        hero_magier = Character(name="Hero Magier", class_name="Magier", level=3, char_definitions=CHARACTER_DEFS, skill_definitions=ALL_SKILLS)

        enemy1 = Character(name="Boblin der Goblin", class_name="Goblin", level=2, char_definitions=CHARACTER_DEFS, skill_definitions=ALL_SKILLS)
        enemy2 = Character(name="Skelly das Skelett", class_name="Skelett", level=2, char_definitions=CHARACTER_DEFS, skill_definitions=ALL_SKILLS)
        enemy3 = Character(name="Gobbo der Goblin", class_name="Goblin", level=1, char_definitions=CHARACTER_DEFS, skill_definitions=ALL_SKILLS)


        print("\nCharaktere erstellt:")
        print(hero_krieger)
        print(hero_magier)
        print(enemy1)
        print(enemy2)
        print(enemy3)

        # Setup Kampfumgebung
        combat_env = Environment()
        combat_env.add_character(hero_krieger)
        combat_env.add_character(hero_magier)
        combat_env.add_character(enemy1)
        combat_env.add_character(enemy2)
        combat_env.add_character(enemy3)


        # Starte den Kampf
        combat_env.run_combat()


    except ValueError as e:
        print(f"FEHLER bei Charaktererstellung oder Setup: {e}")
        import traceback
        traceback.print_exc() # Print detailed traceback for debugging
    except Exception as e:
        print(f"Ein unerwarteter Fehler ist im Hauptblock aufgetreten: {e}")
        import traceback
        traceback.print_exc()

else:
     # This message prints when the script is imported, not run directly
     print("Spiel-Logik-Klassen in rpg_game_logic.py geladen (V11 - Regen erhöht).")
