# -*- coding: utf-8 -*-
"""rpg_ui

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12k8eGP7IeJPL7uj0Ii4iRqSxa_VAHjma
"""

# Generated/Overwritten on: 2025-04-13 12:12:24 # Zeitpunkt aktualisiert (Inhalt von V1 Übernommen)
# rpg_ui.py
# Fügt Level- und XP-Anzeige zur HTML UI hinzu.

from IPython.display import HTML
import re, html
from typing import List, Optional, Any

# Importiere Klassen nur für Typ-Hints, wenn möglich, oder fange ImportError ab
try:
    from rpg_game_logic import Character
except ImportError:
    print("WARNUNG (rpg_ui): Konnte rpg_game_logic nicht importieren. Definiere Platzhalter.")
    class Character: pass

def generate_html_ui(environment: Optional[Any], log_history: List[str]) -> HTML:
    """
    Generiert die HTML-Darstellung für die Spielumgebung und das Kampflog.
    Zeigt jetzt auch Level und XP an.
    """
    # --- CSS Definitionen (leicht angepasst für XP-Bar) ---
    css = """
    <style>
        body { font-family: sans-serif; font-size: 13px; }
        #game-ui { width: 100%; max-width: 900px; margin: 0 auto; }
        .char-container { display: flex; flex-wrap: wrap; justify-content: space-around; margin-bottom: 15px; gap: 15px; }
        .char-box {
            border: 1px solid #ccc; border-radius: 5px; padding: 10px;
            flex-basis: 250px; flex-grow: 1; background-color: #f9f9f9;
            box-shadow: 2px 2px 5px rgba(0,0,0,.1); display: flex; flex-direction: column;
        }
        .char-header { margin-bottom: 5px; }
        .char-name { font-size: 1.2em; font-weight: bold; color: #333; margin-right: 5px;}
        .char-class-level { font-size: 0.9em; color: #555; }
        .resource-bar {
            height: 18px; background-color: #e9ecef; border-radius: 3px;
            margin: 5px 0; overflow: hidden; border: 1px solid #bbb; position: relative;
        }
        .resource-fill { height: 100%; transition: width .3s ease-in-out; float: left; }
        .resource-text {
            position: absolute; width: 100%; text-align: center; color: #fff;
            font-size: 11px; line-height: 18px; font-weight: 700;
            text-shadow: 1px 1px 1px rgba(0,0,0,.5); pointer-events: none;
        }
        /* Spezifische Farben für Balken */
        .hp-bar .resource-fill { background-color: #28a745; } /* Grün */
        .hp-bar.low .resource-fill { background-color: #ffc107; } /* Gelb */
        .hp-bar.critical .resource-fill { background-color: #dc3545; } /* Rot */
        .hp-bar.dead .resource-fill { background-color: #6c757d; } /* Grau */
        .mana-bar .resource-fill { background-color: #007bff; } /* Blau */
        .stamina-bar .resource-fill { background-color: #dc3545; } /* Rot (wie critical HP) */
        .energy-bar .resource-fill { background-color: #ffc107; } /* Gelb (wie low HP) */
        .xp-bar .resource-fill { background-color: #6f42c1; } /* Lila */

        .char-stats { font-size: .9em; margin-top: 8px; line-height: 1.4; }
        .stats-grid { display: grid; grid-template-columns: auto 1fr auto 1fr; gap: 2px 8px; }
        .stats-grid span { white-space: nowrap; }
        .char-effects { font-size: .9em; margin-top: 8px; }
        .char-effects strong { font-size: .9em; display: inline; margin-bottom: 0; }
        .char-effects ul { list-style: none; padding-left: 0; margin: 4px 0 0; display: flex; flex-wrap: wrap; gap: 3px; }
        .char-effects li { border-radius: 3px; padding: 1px 5px; font-size: 10px; border: 1px solid; }
        .effect-good { background-color: #d4edda; border-color: #c3e6cb; color: #155724; }
        .effect-bad { background-color: #f8d7da; border-color: #f5c6cb; color: #721c24; }
        .effect-neutral { background-color: #eee; border-color: #ddd; color: #333; }
        #log-area {
            border: 1px solid #ccc; height: 250px; overflow-y: scroll; padding: 8px;
            font-family: monospace; font-size: .9em; background-color: #fff;
            white-space: pre-wrap; /* Lässt Zeilen umbrechen */ word-wrap: break-word; /* Stellt sicher, dass lange Wörter umgebrochen werden */
            margin-top: 5px; border-radius: 3px;
        }
        .log-line span { display: block; margin-bottom: 1px; padding: 1px 3px; border-radius: 2px; }
        /* Log Farben (unverändert) */
        .log-line .log-damage{color:#721c24;background-color:#f8d7da}
        .log-line .log-heal{color:#155724;background-color:#d4edda}
        .log-line .log-effect-add{color:#004085;background-color:#cce5ff}
        .log-line .log-effect-rem{color:#383d41;background-color:#e2e3e5}
        .log-line .log-defeat{color:#f8f9fa;background-color:#343a40;font-weight:700}
        .log-line .log-info{color:#495057}
        h2, h3 { margin-top: 10px; margin-bottom: 5px; border-bottom: 1px solid #eee; padding-bottom: 3px; }
    </style>
    """

    # --- Hilfsfunktion für Ressourcen-/XP-Balken ---
    def create_resource_bar(current: float, maximum: float, bar_class: str, text_color: str = 'white') -> str:
        if maximum <= 0: return ""
        current = max(0, current)
        percent = min(100, (current / maximum) * 100) if maximum > 0 else 0

        bar_text = f"{int(current)} / {int(maximum)}"
        # Spezialtext für XP, wenn nächstes Level erreicht (oder theoretisch max Level)
        if bar_class == "xp-bar" and maximum == 0: # Annahme: Max Level erreicht, wenn xp_to_next_level 0 ist
             bar_text = "MAX LEVEL"
             percent = 100
        elif bar_class == "xp-bar" and current >= maximum and maximum > 0:
             bar_text = f"{int(current)} / {int(maximum)} (LVL UP!)"
             # Balken trotzdem bei 100% lassen oder überlaufen lassen? Bleiben wir bei 100%.
             percent = 100


        hp_extra_class = ""
        if bar_class == "hp-bar":
            if current <= 0: hp_extra_class = "dead"
            elif percent <= 25: hp_extra_class = "critical"
            elif percent <= 50: hp_extra_class = "low"

        if (bar_class == "hp-bar" and (hp_extra_class in ["low", "critical"])) or bar_class == "energy-bar":
            text_color = '#333'
        elif bar_class == "xp-bar":
            text_color = '#eee' # Heller Text für XP

        return (
            f'<div class="resource-bar {bar_class} {hp_extra_class}">'
            f'<div class="resource-fill" style="width:{percent}%;"></div>'
            f'<div class="resource-text" style="color:{text_color};">{bar_text}</div>'
            f'</div>'
        )

    # --- Haupt-HTML Aufbau ---
    html_parts = [css]
    env_obj = environment
    current_round = getattr(env_obj, 'turn_count', '?')
    hero = getattr(env_obj, 'hero', None)
    enemy = getattr(env_obj, 'enemy', None)
    chars = []
    if hero: chars.append(hero)
    if enemy: chars.append(enemy)
    if not chars and hasattr(environment, 'characters'): chars = getattr(environment, 'characters', [])

    html_parts.append(f'<div id="game-ui"><h2>Runde: {current_round}</h2><div class="char-container">')

    # --- Charakter-Boxen generieren ---
    for char in chars:
        if not isinstance(char, Character): continue # Sicherstellen, dass es unser Character-Objekt ist

        name = getattr(char, "name", "N/A")
        class_name = getattr(char, "class_name", "N/A")
        level = getattr(char, "level", "?")

        html_parts.append('<div class="char-box">')
        html_parts.append(f'<div class="char-header"><span class="char-name">{html.escape(name)}</span><span class="char-class-level">({html.escape(class_name)} Lvl: {level})</span></div>')

        # Ressourcen-Balken
        hp, max_hp = char.current_hp, char.max_hp
        html_parts.append(create_resource_bar(hp, max_hp, "hp-bar"))
        if char.max_mana > 10: html_parts.append(create_resource_bar(char.current_mana, char.max_mana, "mana-bar"))
        if char.max_stamina > 20: html_parts.append(create_resource_bar(char.current_stamina, char.max_stamina, "stamina-bar"))
        if char.max_energy > 20: html_parts.append(create_resource_bar(char.current_energy, char.max_energy, "energy-bar"))

        # XP-Balken
        current_xp = getattr(char, 'current_xp', 0)
        xp_next = getattr(char, 'xp_to_next_level', 0) # Wichtig: Default 0, falls Max Level
        html_parts.append(create_resource_bar(current_xp, xp_next, "xp-bar"))

        # Stats
        get_s = getattr(char, 'get_stat', lambda n: 0)
        html_parts.append('<div class="char-stats stats-grid">')
        html_parts.append(f'<span>Ang:</span> <span>{get_s("angriff")}</span><span>Vert:</span> <span>{get_s("verteidigung")}</span>')
        html_parts.append(f'<span>Mag:</span> <span>{get_s("magiekraft")}</span><span>Krit(%):</span> <span>{get_s("krit_chance"):.1f}</span>')
        html_parts.append('</div>')

        # Effekte
        html_parts.append('<div class="char-effects"><strong>Effekte:</strong> ')
        effects = getattr(char, 'active_effects', {})
        if effects and isinstance(effects, dict):
            html_parts.append('<ul>')
            # Sortiere Effekte für konsistente Anzeige
            for effect_name, data in sorted(effects.items()):
                if not isinstance(data, dict): continue
                mods = data.get('modifiers', {})
                is_buff = any(v>0 for k,v in mods.items() if isinstance(k,str) and k.startswith('mod_')) or mods.get('dot_heal',0)>0
                is_debuff = any(v<0 for k,v in mods.items() if isinstance(k,str) and k.startswith('mod_')) or mods.get('dot_damage',0)>0
                css_class = "effect-good" if is_buff and not is_debuff else "effect-bad" if is_debuff and not is_buff else "effect-neutral"
                dur = data.get('duration',0); dur_s = f"{dur}" if dur!=9999 else "∞"
                mod_s = ", ".join([f"{k.replace('mod_','').capitalize()}{v:+d}" if k.startswith("mod_") else f"{k}:{v}" for k,v in mods.items()])
                html_parts.append(f'<li class="{css_class}" title="{html.escape(mod_s)}">{html.escape(effect_name)}({dur_s})</li>')
            html_parts.append('</ul>')
        else: html_parts.append(' Keine')
        html_parts.append('</div>') # Ende char-effects
        html_parts.append('</div>') # Ende char-box

    html_parts.append('</div>') # Ende char-container

    # --- Kampf-Log ---
    html_parts.append('<hr><h3>Kampf-Log</h3><div id="log-area"><pre>')
    log_lines = []
    log_keywords = { "defeat": ["besiegt"], "damage": ["Schaden", "DoT", "attackiert", "verfehlt"], "heal": ["geheilt", "HoT", "Heilung"], "effect-add": ["angewendet", "aktualisiert", "setzt", "Segnen", "Vergiften", "Schwächen", "verbessern"], "effect-rem": ["Entferne", "abgelaufen"], "info": ["Level Up"] }
    for line in log_history:
        escaped_line = html.escape(str(line)); log_class = "log-info"
        for css_type, words in log_keywords.items():
            if any(re.search(r'\b'+re.escape(w)+r'\b', line, re.IGNORECASE) for w in words):
                log_class = f"log-{css_type}"; break
        log_lines.append(f'<span class="log-line"><span class="{log_class}">{escaped_line}</span></span>')
    html_parts.append("\n".join(log_lines))
    html_parts.append('</pre></div></div>') # Ende log-area und game-ui

    return HTML("".join(html_parts))

print("UI-Funktion in rpg_ui.py geschrieben/überschrieben (Level/XP Anzeige V1).")