name: RPG Development Assistant

on:
  workflow_dispatch: # Ermöglicht das manuelle Starten des Workflows
  push: # Startet den Workflow bei jedem Push auf das Repository
    branches:
      - main # Nur die main-Branch wird überwacht

jobs:
  prompt-assistant:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Send Master-Prompt to the AI
      - name: Send Master-Prompt to AI
        id: send_prompt
        run: |
          echo "Sende Master-Prompt an die KI..."
          RESPONSE=$(curl -X POST "https://api.openai.com/v1/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "text-davinci-003",
              "prompt": "'"$(cat master_prompt.txt)"'",
              "max_tokens": 1000
            }')
          echo "$RESPONSE" > response.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # 3. Speichere die Antwort in einer Datei
      - name: Save AI response
        run: |
          echo "Speichere Antwort..."
          cat response.json
          mv response.json ai_response.json

      # 4. Optional: Antwort als Kommentar hinzufügen
      - name: Create a comment on the commit
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.run_id }}
          body: |
            **Antwort von der KI:**
            ```json
            $(cat ai_response.json)
            ```